# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biggest.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(662, 601)
        Dialog.setMaximumSize(QtCore.QSize(1080, 1369))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 233, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 190, 211))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 245, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 181, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 233, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 190, 211))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 245, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 181, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 233, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 190, 211))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 141, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 245, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        Dialog.setPalette(palette)
        self.verticalSliderCholestrol = QtWidgets.QSlider(Dialog)
        self.verticalSliderCholestrol.setGeometry(QtCore.QRect(610, 140, 16, 160))
        self.verticalSliderCholestrol.setMinimum(150)
        self.verticalSliderCholestrol.setMaximum(350)
        self.verticalSliderCholestrol.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderCholestrol.setInvertedControls(False)
        self.verticalSliderCholestrol.setObjectName("verticalSliderCholestrol")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 30, 91, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 111, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 81, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(490, 140, 111, 17))
        self.label_4.setObjectName("label_4")
        self.verticalScrollBarPulseRate = QtWidgets.QScrollBar(Dialog)
        self.verticalScrollBarPulseRate.setGeometry(QtCore.QRect(100, 140, 12, 160))
        self.verticalScrollBarPulseRate.setAutoFillBackground(False)
        self.verticalScrollBarPulseRate.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0.722, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:0.123762 rgba(250, 188, 174, 255), stop:0.376238 rgba(243, 109, 79, 255), stop:0.638614 rgba(237, 43, 0, 255));")
        self.verticalScrollBarPulseRate.setMinimum(39)
        self.verticalScrollBarPulseRate.setMaximum(180)
        self.verticalScrollBarPulseRate.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBarPulseRate.setInvertedAppearance(True)
        self.verticalScrollBarPulseRate.setInvertedControls(False)
        self.verticalScrollBarPulseRate.setObjectName("verticalScrollBarPulseRate")
        self.horizontalScrollBarSugarLevel = QtWidgets.QScrollBar(Dialog)
        self.horizontalScrollBarSugarLevel.setGeometry(QtCore.QRect(190, 30, 421, 16))
        self.horizontalScrollBarSugarLevel.setAutoFillBackground(True)
        self.horizontalScrollBarSugarLevel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:0.686567 rgba(204, 0, 0, 255));")
        self.horizontalScrollBarSugarLevel.setMinimum(50)
        self.horizontalScrollBarSugarLevel.setMaximum(500)
        self.horizontalScrollBarSugarLevel.setPageStep(1)
        self.horizontalScrollBarSugarLevel.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBarSugarLevel.setInvertedAppearance(False)
        self.horizontalScrollBarSugarLevel.setInvertedControls(False)
        self.horizontalScrollBarSugarLevel.setObjectName("horizontalScrollBarSugarLevel")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(190, 70, 431, 61))
        self.groupBox.setObjectName("groupBox")
        self.horizontalSliderSystolic = QtWidgets.QSlider(self.groupBox)
        self.horizontalSliderSystolic.setGeometry(QtCore.QRect(0, 20, 391, 16))
        self.horizontalSliderSystolic.setMinimum(70)
        self.horizontalSliderSystolic.setMaximum(190)
        self.horizontalSliderSystolic.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderSystolic.setObjectName("horizontalSliderSystolic")
        self.horizontalSliderDiastolic = QtWidgets.QSlider(self.groupBox)
        self.horizontalSliderDiastolic.setGeometry(QtCore.QRect(0, 40, 391, 16))
        self.horizontalSliderDiastolic.setMinimum(10)
        self.horizontalSliderDiastolic.setMaximum(200)
        self.horizontalSliderDiastolic.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderDiastolic.setObjectName("horizontalSliderDiastolic")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 300, 641, 261))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEditSugarLevel = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditSugarLevel.setEnabled(False)
        self.lineEditSugarLevel.setGeometry(QtCore.QRect(30, 40, 113, 25))
        self.lineEditSugarLevel.setObjectName("lineEditSugarLevel")
        self.lineEditBPlevel = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditBPlevel.setEnabled(False)
        self.lineEditBPlevel.setGeometry(QtCore.QRect(510, 40, 113, 25))
        self.lineEditBPlevel.setObjectName("lineEditBPlevel")
        self.lineEditPulseRate = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditPulseRate.setEnabled(False)
        self.lineEditPulseRate.setGeometry(QtCore.QRect(30, 230, 113, 25))
        self.lineEditPulseRate.setObjectName("lineEditPulseRate")
        self.lineEditCholestrol = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditCholestrol.setEnabled(False)
        self.lineEditCholestrol.setGeometry(QtCore.QRect(510, 230, 113, 25))
        self.lineEditCholestrol.setObjectName("lineEditCholestrol")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(40, 20, 81, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(530, 20, 61, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(50, 210, 71, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(530, 210, 81, 20))
        self.label_8.setObjectName("label_8")
        self.plainTextEditResult = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEditResult.setGeometry(QtCore.QRect(30, 80, 581, 121))
        self.plainTextEditResult.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.plainTextEditResult.setObjectName("plainTextEditResult")
        self.pushButtonAnalyse = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonAnalyse.setGeometry(QtCore.QRect(260, 210, 89, 25))
        self.pushButtonAnalyse.setAutoFillBackground(False)
        self.pushButtonAnalyse.setStyleSheet("background-color: rgb(204, 0, 0);")
        self.pushButtonAnalyse.setObjectName("pushButtonAnalyse")
        self.verticalSliderCholestrol.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.verticalScrollBarPulseRate.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.horizontalScrollBarSugarLevel.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sugar Level"))
        self.label_2.setText(_translate("Dialog", "Blood Pressure"))
        self.label_3.setText(_translate("Dialog", "Pulse Rate"))
        self.label_4.setText(_translate("Dialog", "Cholestrol level"))
        self.groupBox.setTitle(_translate("Dialog", "systolic and diastolic"))
        self.groupBox_2.setTitle(_translate("Dialog", "Result:"))
        self.label_5.setText(_translate("Dialog", "sugar level"))
        self.label_6.setText(_translate("Dialog", "BP level"))
        self.label_7.setText(_translate("Dialog", "Pulse Rate"))
        self.label_8.setText(_translate("Dialog", "Cholestrol"))
        self.pushButtonAnalyse.setText(_translate("Dialog", "Analyse"))
